# Generated by Django 2.2.19 on 2023-11-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('site', models.URLField(max_length=254, verbose_name='Сайт')),
            ],
        ),
    ]
