version: '3'


volumes:
  pg_data_production:
  static_volume:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  events:
    image: kotovmaxim/events_backend
    env_file: .env
    volumes:
      - static_volume:/events_static
  gateway:
    image: kotovmaxim/events_gateway
    volumes:
      - static_volume:/staticfiles/
    ports:
      - 8000:80
