# Generated by Django 4.2.6 on 2023-10-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0002_remove_message_text_message_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='subscription',
            field=models.BooleanField(default=False, verbose_name='Подписка'),
        ),
    ]
