# Generated by Django 4.2.6 on 2023-10-22 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0003_alter_message_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription', models.BooleanField(default=False, verbose_name='Подписка')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Время подписки')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tg_bot.profile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
