# Generated by Django 4.2.6 on 2023-10-22 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0004_subscription_delete_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
    ]
